<a href="https://colab.research.google.com/github/IbukunGracey/PyTorch-Basics/blob/main/01_Torch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is PyTorch?

PyTorch is an open-source machine learning framework based on the Torch library, primarily used for applications like computer vision and natural language processing. It provides tools and libraries that simplify the design, training, and deployment of deep learning models.

It’s a Python-based scientific computing package.

PyTorch's dynamic computational graph allows for flexibility and easier debugging, making it popular in research and development. It supports both eager and graph execution modes and offers strong GPU acceleration capabilities, similar to NumPy but with added deep learning functionalities.


### Pytorch Workflow Fundermentals

The essence of machine learning and deep learning is to take some data from the past, build an algorithm (like a neural network) to discover patterns in it and use the discovered patterns to predict the future.

There are many ways to do this and many new ways are being discovered all the time.

But let's start small.

The image below shows a standard pytorch workflow.

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/01_a_pytorch_workflow.png" width=900 alt="a pytorch workflow flowchat"/>

# Getting Started

Now let's import what we'll need for this module.

We're going to get `torch`, `torch.nn` (`nn` stands for neural network and this package contains the building blocks for creating neural networks in PyTorch) and `matplotlib`.



#### Torch

• When you import the torch library in Python using import
torch, you are indeed importing the torch module, which is
part of the PyTorch library.

• This module provides access to the core functionalities of
PyTorch, including tensor operations, neural network
building blocks, optimization algorithms, and more.

• Once imported, you can use the functions, classes, and
submodules provided by torch to develop machine
learning models and perform various tasks in PyTorch.


In [ ]:
import torch as t
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

# Check PyTorch version
t.__version__

'2.6.0+cu124'

#### **Empty Method**

The . empty() method creates a tensor with uninitialized data. This means that the tensor is allocated memory without setting its values, which may contain arbitrary data (such as NaNs or other undefined values)

In [ ]:
# construct a 5x3 matrix
a=t.empty(5,3)
a

tensor([[ 0.0000e+00,  0.0000e+00,  2.3197e-16],
        [ 0.0000e+00,  1.8473e-18,  0.0000e+00],
        [-1.6868e-36,  4.5398e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

**To DO 1: Create an empty tensor of shape 5,5**

# Tensors

#### Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

#### **Construct a tensor directly from data:**

In [ ]:
c=t.tensor(10)
c

tensor(10)

In [ ]:
# c.ndim

In [ ]:
d=t.tensor([5.5,3])
d

tensor([5.5000, 3.0000])

In [ ]:
 v = t.tensor([[7,7,7],[5,6,7]])
 print(v)
 print(v.ndim)
 print(v.shape)

tensor([[7, 7, 7],
        [5, 6, 7]])
2
torch.Size([2, 3])


#### To DO 2:
Given a list of lists Q2 = [[2,3,4,5], [2,3,4,7], [7,8,9,0]]
1. Create a tensor with list Q2
2. What is the dimension
3. What is the shape

In [ ]:
Q2 = [[2,3,4,5], [2,3,4,7], [7,8,9,0]]

#### Random Tensors

In [ ]:
# Random no matrix
b=t.rand(5,3)
b

tensor([[0.8749, 0.5867, 0.4056],
        [0.1836, 0.3294, 0.4770],
        [0.9495, 0.6079, 0.2189],
        [0.6634, 0.0989, 0.7883],
        [0.3182, 0.6416, 0.9233]])

In [ ]:
c=t.randn(5,3)
c

tensor([[-0.0051, -1.2252, -1.6129],
        [ 1.4485, -1.2999, -0.2368],
        [ 0.0909, -0.3881,  0.3276],
        [-1.4214,  0.2496, -0.6775],
        [ 0.1939,  0.0062,  0.8614]])

In [ ]:
# Returns a tensor with the same size as input that is filled
# with random numbers from a normal distribution with mean 0 and variance 1.
a=t.randn_like(c,dtype=t.float32) # all data type work except "Complex"
a

tensor([[-0.3897,  1.2451,  1.2166],
        [ 0.4350,  0.3161, -1.6699],
        [ 0.6527,  0.5103,  0.4275],
        [-0.7809, -1.4232, -0.4888],
        [-0.6705, -0.3071,  0.0254]])

In [ ]:
a=t.randn_like(a,dtype=t.float)             # override dtype!
a                                           # result has the same size

tensor([[-0.1519, -0.4778, -0.1715],
        [-0.6455,  0.0104,  0.7999],
        [-0.2885,  1.3047,  0.2799],
        [ 0.2657, -0.7263,  2.4594],
        [ 0.7841, -1.2691, -1.1586]])

In [ ]:
a.size()

torch.Size([5, 3])

In [ ]:
#d=t.random(5,3)   # random not work in pytorch

In [ ]:
# Random Image Tensors
random_image_size= t.rand(size=(3, 244,244))
print(random_image_size)
print(f"Random image shape: {random_image_size.shape}")
print(f"Random image dimension: {random_image_size.ndim}")
print(f"Random image datatype: {random_image_size.dtype}")

tensor([[[0.3839, 0.1482, 0.2604,  ..., 0.5855, 0.4327, 0.9622],
         [0.3141, 0.9907, 0.3895,  ..., 0.6337, 0.7489, 0.0562],
         [0.7593, 0.0243, 0.7638,  ..., 0.4868, 0.7573, 0.9337],
         ...,
         [0.9205, 0.7057, 0.8475,  ..., 0.3267, 0.3184, 0.3764],
         [0.1166, 0.3352, 0.9336,  ..., 0.4559, 0.6165, 0.3809],
         [0.8009, 0.5072, 0.3642,  ..., 0.0555, 0.2339, 0.0602]],

        [[0.1322, 0.0159, 0.6616,  ..., 0.7773, 0.0018, 0.7159],
         [0.2592, 0.3506, 0.5693,  ..., 0.6080, 0.5556, 0.9506],
         [0.3797, 0.2247, 0.0245,  ..., 0.4274, 0.3143, 0.8952],
         ...,
         [0.5434, 0.8513, 0.2053,  ..., 0.0391, 0.4638, 0.7936],
         [0.6188, 0.1490, 0.3450,  ..., 0.6445, 0.5785, 0.8872],
         [0.9221, 0.0123, 0.6863,  ..., 0.7332, 0.0121, 0.3800]],

        [[0.3693, 0.4218, 0.4933,  ..., 0.6347, 0.5654, 0.0333],
         [0.1084, 0.5175, 0.9963,  ..., 0.5020, 0.3407, 0.6511],
         [0.7675, 0.1867, 0.9048,  ..., 0.8359, 0.5251, 0.

In [ ]:

# Convert the random image tensor created to an actual image
import torchvision.transforms as T
from PIL import Image

# Create a ToPILImage transform
transform = T.ToPILImage()

# Convert the tensor to a PIL Image
image = transform(random_image_size)

# Save the image (optional)
image.save("random_image2.png")

#### Range and Arange Function

In PyTorch, both torch.range and torch.arange are used to create 1-D tensors with sequential values. However, torch.arange is the preferred and more versatile option as ** torch.range is deprecated and its behavior is inconsistent with Python's built-in range.** see code output below.

The torch.arange generates a tensor with values from start to end (exclusive) with a specified step, while torch.range produces values from start to end (inclusive) with a step.

In [ ]:
one_to_ten = t.range(0,10)
one_to_ten

<ipython-input-8-b1db95d2c089>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = t.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
#Note this is different from the range function
b=t.arange(10)
b

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x= t.arange(0,19)
print(x)
print(t.min(x).item())  # Get the minimum value
print(t.max(x).item())  # Get the maximum value
print(t.mean(x.type(t.float32)).item())   # Get the mean value

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18])
0
18
9.0
9.0


#### Zeros

Construct a matrix filled zeros and of dtype long:


In [ ]:
a=t.zeros(10)
b= t.ones(10)
c=t.full((2,3), 13)
d= t.empty(10)
print(a)
print(b)
print(c)
print(d)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[13, 13, 13],
        [13, 13, 13]])
tensor([ 2.3294e-39,  4.4449e-41,  1.3673e-29,  0.0000e+00,  1.5077e-38,
         0.0000e+00, -7.2692e+20,  4.4446e-41, -7.3972e+20,  4.4446e-41])


In [ ]:
# You can specify the data types
b=t.zeros(5,3,dtype=t.long)
b

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### new_

You can create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user.

    - ones
    - empty
    - full
    - zeros

In [ ]:
new = t.ones(5,3, dtype=t.double)
new

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [ ]:
a

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Using the new_* methods recreate new tensors from a
a=a.new_ones(5,3,dtype=t.double)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [ ]:
b=a.new_empty(5,3,dtype=t.double)
b

tensor([[6.7310e-310, 4.9011e-317, 6.7310e-310],
        [6.7310e-310, 4.9011e-317, 6.7310e-310],
        [6.7310e-310, 5.3171e-317, 5.3157e-317],
        [5.3157e-317, 6.7307e-310, 6.7307e-310],
        [5.3171e-317, 6.7307e-310, 6.7307e-310]], dtype=torch.float64)

In [ ]:
c=a.new_full((5,3),10, dtype=t.double)
c

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]], dtype=torch.float64)

In [ ]:
d=a.new_zeros(5,3,dtype=t.double)
d

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

#### Type Conversion

This code initializes a 2-dimensional tensor named "my_tensor" with the values [[1,2,3], [4,5,6]],
using the data type float32, stored on the CPU (default device), and with gradient tracking
disabled (requires_grad=False). The resulting tensor "my_tensor" is a 2x3 matrix of floating-point
numbers, ready for computation but not tracking gradients for automatic differentiation.


In [ ]:
my_tensor=  t.tensor([[1,2,3],[4,5,6]],dtype=t.float32,device=None,requires_grad=False)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
float_16 = my_tensor.type(t.float16)
float_16

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [ ]:
float_16.size()

torch.Size([2, 3])

#### ``torch.Size`` is a tuple, so it supports all tuple operations.



# Operations

#### There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [ ]:
a

tensor([[-0.3897,  1.2451,  1.2166],
        [ 0.4350,  0.3161, -1.6699],
        [ 0.6527,  0.5103,  0.4275],
        [-0.7809, -1.4232, -0.4888],
        [-0.6705, -0.3071,  0.0254]])

In [ ]:
b=t.randn(5,3)
b

tensor([[-4.4916e-01, -1.0475e+00, -1.1443e+00],
        [ 1.1490e+00,  8.2445e-03,  2.3795e-01],
        [ 1.3454e+00,  8.4939e-02,  1.2923e+00],
        [ 1.1949e+00,  1.6875e+00, -1.5775e+00],
        [ 1.2355e-04,  8.6563e-01, -1.0923e+00]])

In [ ]:
print(a+b)

tensor([[-0.8388,  0.1976,  0.0723],
        [ 1.5840,  0.3243, -1.4320],
        [ 1.9982,  0.5952,  1.7198],
        [ 0.4140,  0.2643, -2.0663],
        [-0.6704,  0.5585, -1.0668]])


In [ ]:
t.add(a,b)

tensor([[-1.5582,  1.6605,  0.9676],
        [ 0.6581, -0.6282, -1.7807],
        [-0.9989,  0.9289, -0.1081],
        [-0.6943, -1.3303, -0.2930],
        [-1.2958, -1.0085,  0.5449]])

### Addition: providing an output tensor as argument



In [ ]:
res = t.empty(5,3)
res

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
t.add(a,b,out=res)
print(res)             # res value is changed

tensor([[-0.8388,  0.1976,  0.0723],
        [ 1.5840,  0.3243, -1.4320],
        [ 1.9982,  0.5952,  1.7198],
        [ 0.4140,  0.2643, -2.0663],
        [-0.6704,  0.5585, -1.0668]])


### Addition: in-place

In [ ]:
b

tensor([[-4.4916e-01, -1.0475e+00, -1.1443e+00],
        [ 1.1490e+00,  8.2445e-03,  2.3795e-01],
        [ 1.3454e+00,  8.4939e-02,  1.2923e+00],
        [ 1.1949e+00,  1.6875e+00, -1.5775e+00],
        [ 1.2355e-04,  8.6563e-01, -1.0923e+00]])

#### More Operations


In [ ]:
a=t.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
b=t.zeros(3,3)
a+b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
c=t.arange(9).reshape(3,3)
c

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
c+a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
c.size()

torch.Size([3, 3])

In [ ]:
c.shape

torch.Size([3, 3])

In [ ]:
c.ndim

2

In [ ]:
c-a

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.],
        [ 5.,  6.,  7.]])

In [ ]:
a*c

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [ ]:
c/a

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [ ]:
c//a

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [ ]:
c%a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# add a to b
b.add_(a)
print(b)   # b is changed because "add_" (underscore) has an inplace function

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


Note: Any operation that mutates a tensor in-place is post-fixed with an ``_``. For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.

### PyTorch Data Manipulations

#### 1. Convert an image to tensors

#### 2. Convert tensors to image:

When converting images back to a tensor:Ensure the tensor has the correct shape and type:
The tensor should have a shape of (C, H, W) where C is the number of channels (e.g., 3 for RGB), H is the height, and W is the width.
If the tensor has a batch dimension (B, C, H, W), select a single image from the batch using indexing (e.g., tensor[0] to get the first image).
The data type of the tensor should ideally be float32 and the values should be normalized between 0 and 1 or 0 and 255.

In [ ]:
# Import the required libraries
# Using Pil
from PIL import Image
import torchvision.transforms as transforms
# import torchvision.transforms as T

# Read the image
image = Image.open('penguins.jpg')

# Define a transform to convert the image to tensor
transform = transforms.ToTensor()

# Convert the image to PyTorch tensor
tensor = transform(image)

# print the converted image tensor
print(tensor)

tensor([[[0.4471, 0.4471, 0.4706,  ..., 0.3373, 0.3412, 0.3412],
         [0.4510, 0.4471, 0.4627,  ..., 0.3373, 0.3373, 0.3373],
         [0.4667, 0.4549, 0.4588,  ..., 0.3490, 0.3490, 0.3451],
         ...,
         [0.6824, 0.4941, 0.5216,  ..., 0.4549, 0.4275, 0.3412],
         [0.4275, 0.5882, 0.6784,  ..., 0.4549, 0.4549, 0.3608],
         [0.3765, 0.3529, 0.4627,  ..., 0.3804, 0.4275, 0.3451]],

        [[0.6824, 0.6824, 0.7059,  ..., 0.6314, 0.6353, 0.6353],
         [0.6863, 0.6824, 0.6980,  ..., 0.6314, 0.6314, 0.6314],
         [0.6980, 0.6863, 0.6941,  ..., 0.6353, 0.6353, 0.6314],
         ...,
         [0.7216, 0.5333, 0.5647,  ..., 0.5294, 0.5059, 0.4235],
         [0.4667, 0.6275, 0.7216,  ..., 0.5294, 0.5333, 0.4431],
         [0.4157, 0.3922, 0.5059,  ..., 0.4549, 0.5059, 0.4275]],

        [[0.8157, 0.8157, 0.8392,  ..., 0.7882, 0.7922, 0.7922],
         [0.8196, 0.8157, 0.8314,  ..., 0.7882, 0.7882, 0.7882],
         [0.8314, 0.8196, 0.8275,  ..., 0.7961, 0.7961, 0.

In [ ]:
print('Tensor shape - ', tensor.shape)
print('Tensor dim- ', tensor.ndim)
print('Tensor size - ', tensor.dtype)

Tensor shape -  torch.Size([3, 500, 700])
Tensor dim-  3
Tensor size -  torch.float32


In [ ]:
#convert tensor back into image
# Create a ToPILImage transform
transform_new = transforms.ToPILImage()

# Convert the tensor to a PIL Image
image = transform_new(tensor)

# Display the image (optional)
image.show()

# Save the image (optional)
image.save("random_image.png")

#### Resizing Tensors

If you want to resize/reshape tensor, you can use torch.view:



In [ ]:
x=t.randn(4,4)
print(x)
print()             # space line

y=x.view(16)        #  "view" converted size of 2D array into 1D array or vector
print(y)
print()

z=x.view(-1,8)      # reshape into 2x8 matrix(2D)  [-1 automatic take row as mapping]
print(z)

tensor([[-0.6024, -0.4145, -1.0802, -0.6746],
        [ 1.0682, -0.3147,  0.3193,  0.3219],
        [ 0.1404,  0.3327, -2.0426,  0.7772],
        [-0.5795,  2.3855,  0.0156,  0.1679]])

tensor([-0.6024, -0.4145, -1.0802, -0.6746,  1.0682, -0.3147,  0.3193,  0.3219,
         0.1404,  0.3327, -2.0426,  0.7772, -0.5795,  2.3855,  0.0156,  0.1679])

tensor([[-0.6024, -0.4145, -1.0802, -0.6746,  1.0682, -0.3147,  0.3193,  0.3219],
        [ 0.1404,  0.3327, -2.0426,  0.7772, -0.5795,  2.3855,  0.0156,  0.1679]])


In [ ]:
a=x.view(2,-1)   # automatic take column size
a

tensor([[-0.6024, -0.4145, -1.0802, -0.6746,  1.0682, -0.3147,  0.3193,  0.3219],
        [ 0.1404,  0.3327, -2.0426,  0.7772, -0.5795,  2.3855,  0.0156,  0.1679]])

In [ ]:
x.size() , y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

#### If you have a one element tensor, use .item() to get the value as a Python number



In [ ]:
x=t.randn(1)
print(x)
print(x.item())

tensor([-0.6232])
-0.6232212781906128


In [ ]:
y=t.randn([10])
print(x)
print(x.item())

tensor([-0.6232])
-0.6232212781906128


In [ ]:
x=t.randn(1,2)
print(x)
print(x.item())      # only one element converted

tensor([[0.5860, 0.2045]])


RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

## Read later:

### 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described here <http://pytorch.org/docs/torch>_.



# NumPy Bridge


#### It is possible to convert a Torch Tensor to a NumPy array and vice versa.
#### The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.



#### Converting a Torch Tensor to a NumPy Array


In [ ]:
a=t.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


#### See how the numpy array changed in value.



In [ ]:
a.add_(1)   # add_(value)    value must be tensor not numpy or other type
print(a)
print(b)    # a changes also make in numpy array b

tensor([[ 0.8481,  0.5222,  0.8285],
        [ 0.3545,  1.0104,  1.7999],
        [ 0.7115,  2.3047,  1.2799],
        [ 1.2657,  0.2737,  3.4594],
        [ 1.7841, -0.2691, -0.1586]])
tensor([[ 2.0615,  0.0172, -1.1664],
        [-0.0359,  0.7513, -0.2906],
        [-0.7226, -0.8967, -0.3990],
        [ 1.7552, -0.8289, -0.0724],
        [ 0.7222,  0.3221, -0.5237]])


#### Converting NumPy Array to Torch Tensor ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a=np.ones(5)
b=t.from_numpy(a)
print(a,b)
print()

np.add(a,1,out=a)  #out=a means changes add changed saved in a
print(a)
print(b)           # b(tensor) value is changed

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### All the Tensors on the CPU except a CharTensor support converting to NumPy and back.



# CUDA Tensors


#### Tensors can be moved onto any device using the .to method.


In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
import torch as t
x= t.empty(2,3)

if t.cuda.is_available():
    device=t.device("cuda")                # a CUDA device object
    y=t.ones_like(x,device=device)       # directly create a tensor on GPU
    x=x.to(device)
    print(x)                      # or just use strings ``.to("cuda")``
    z=x+y
    print(z)
    print(z.to("cpu",t.double))            # ``.to`` can also change dtype together!

tensor([[1.6401e-21, 0.0000e+00, 1.6400e-21],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


# Indexing


In [ ]:
c = t.tensor([[1,2,3],[4,5,6],[7,8,9]])
c

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
c[0]

tensor([1, 2, 3])

In [ ]:
c[1:]

tensor([[4, 5, 6],
        [7, 8, 9]])

In [ ]:
c[:1]

tensor([[1, 2, 3]])

In [ ]:
c[1:,:1]

tensor([[4],
        [7]])

In [ ]:
a!=c

NameError: name 'a' is not defined

In [ ]:
a==c

tensor([[False,  True, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
a<c

tensor([[False, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [ ]:
a>c

tensor([[ True, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
a=t.tensor(10)
a

tensor(10)

In [ ]:
b=t.tensor([[1,2,3],[4,5,6],[7,8,9]])
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
b.dtype

torch.int64

# Scalar

In [ ]:
a=t.tensor(12)
a

tensor(12)

In [ ]:
a.ndim

0

In [ ]:
a.shape

torch.Size([])

In [ ]:
a.data

tensor(12)

In [ ]:
a.shape

torch.Size([])

In [ ]:
a.dtype

torch.int64

In [ ]:
b=t.tensor((10,20,30))  # more than 1 value u given value as a tuple
b

tensor([10, 20, 30])

In [ ]:
c=t.tensor(((1,2,3),(4,5,6)))
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
c=t.tensor((((1,2,3),(4,5,6)))) # bracket increased but got 2D array
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
d=t.tensor([10,10.5,True])
d

tensor([10.0000, 10.5000,  1.0000])

In [ ]:
e=t.tensor(("hello"))  ## Texts are not allowed
# e=t.tensor(["hi"])
e

TypeError: new(): invalid data type 'str'

In [ ]:
a=t.tensor([10,20])
print(type(a))

<class 'torch.Tensor'>


# vector or 1D tensor

In [ ]:
a=t.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
a.data

tensor([1, 2, 3])

# 2D tensor

In [ ]:
c=t.tensor([(1,2,3)])
c

tensor([[1, 2, 3]])

In [ ]:
c=t.tensor([(1,2,True),(4,5,6)])
print(c)
c.dtype
# same as t.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 1],
        [4, 5, 6]])


torch.int64

In [ ]:
c=t.tensor([(1,2,3.15),(4,5,6)])
print(c)
c.dtype
# same as t.tensor([[1,2,3],[4,5,6]])

tensor([[1.0000, 2.0000, 3.1500],
        [4.0000, 5.0000, 6.0000]])


torch.float32

In [ ]:
c=t.tensor([(1,2,3),(4,5,6)])
print(c)
print(c.size())
c.dtype
# same as t.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


torch.int64

In [ ]:
a=t.tensor([2+3j])   # torch not support complex n string
# b=t.tensor(["hi",1,2])
# print(a)
print(a)

tensor([2.+3.j])


In [ ]:
a=t.tensor([[1,2],[3,4]],dtype=t.complex64)
a     # complex not working in tensor type

tensor([[1.+0.j, 2.+0.j],
        [3.+0.j, 4.+0.j]])

In [ ]:
a=t.tensor([[1,2],[3,4]],dtype=t.long)
a     # complex not working in tensor type

tensor([[1, 2],
        [3, 4]])

In [ ]:
a=t.tensor([[1,2],[3,4]],dtype=t.bool)
a     # complex not working in tensor type

tensor([[True, True],
        [True, True]])

In [ ]:
b=t.arange(12).reshape(4,3)
b

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
c=t.tensor(((1,2),(3,4)))
c

tensor([[1, 2],
        [3, 4]])

In [ ]:
c.shape

torch.Size([2, 2])

In [ ]:
c.size()

torch.Size([2, 2])

# 3D Tensor

In [ ]:
a=t.tensor([[[1,2],[3,4]]])
a

tensor([[[1, 2],
         [3, 4]]])

In [ ]:
b=t.tensor([((1,2),(3,4))])
b

tensor([[[1, 2],
         [3, 4]]])

In [ ]:
c.size()

torch.Size([1, 2, 3])

In [ ]:
c=t.tensor([[(1,2,3),(4,5,6)]])
c

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
# tried for 3D but got 2D array
d=t.tensor((([[1,2],[3,4]])))
d

tensor([[1, 2],
        [3, 4]])

In [ ]:
c.ndim

3

In [ ]:
c.shape

torch.Size([1, 2, 3])

# Transposition

In [ ]:
a=t.tensor([1,2,3])
t.transpose(a,0,0)  # not possible bcoz they have only one axis

tensor([1, 2, 3])

In [ ]:
b=t.tensor([[1,2],[3,4],[5,6]])
print(b.transpose)
print(t.transpose(b,1,0),"\n")  # both axis not equal so no transpose
b.T

<built-in method transpose of Tensor object at 0x000002B655F9BA98>
tensor([[1, 3, 5],
        [2, 4, 6]]) 



tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
a=t.tensor([[1,2],[3,4]])
print(a)
t.transpose(a,0,1)         # axis=0 replace with axis=1

tensor([[1, 2],
        [3, 4]])


tensor([[1, 3],
        [2, 4]])

In [ ]:
a=t.tensor([[1,2],[3,4]])
t.transpose(a,1,0)

tensor([[1, 3],
        [2, 4]])

In [ ]:
a=t.tensor([(1,2,3),(4,5,6)])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#transpose
a.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## unsqueeze()

unsqueeze() adds a new dimension of size one to a tensor at a specified position. This is useful for reshaping tensors to be compatible with operations that require specific input dimensions, such as broadcasting or matrix multiplication

In [ ]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
a.unsqueeze(0)  # not changed the original data

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
a.unsqueeze(1)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [ ]:
a.unsqueeze(2)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [ ]:
a     # original data not changed by "unsqueeze"

tensor([[1, 2, 3],
        [4, 5, 6]])

## squeeze()
In PyTorch, the squeeze() function removes dimensions of size 1 from a tensor. If a dimension is not of size 1, it is not removed. It can be used with or without a specified dimension. If a dimension is specified, only that dimension is squeezed. If no dimension is specified, all dimensions of size 1 are removed.


In [ ]:
print(a)
print(a.ndim)

tensor([[1, 2, 3],
        [4, 5, 6]])
2


In [ ]:
y = a.unsqueeze(1) #this adds a dimension to 'a'
print(y)
print(y.ndim)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
3


In [ ]:
y.squeeze(1) #this removes a dimension from a

tensor([[1, 2, 3],
        [4, 5, 6]])

## resize()

In PyTorch, "resize" refers to changing the dimensions of a tensor (an n-dimensional array). It's a common operation, especially when working with images or other data that needs to conform to specific input shapes for neural networks or other processing steps. Resizing can be done using various functions, each with slightly different behavior:

In [ ]:
a.resize(1,3,2)   # not chnaged the original data

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [ ]:
a  # not effect by "resize"

tensor([[1, 2, 3],
        [4, 5, 6]])

## flatten()

In PyTorch, "flatten" refers to the operation of reshaping a tensor into a one-dimensional array. It essentially collapses all the dimensions of the tensor into a single dimension, while preserving the order of elements. This is commonly used to prepare data for fully connected layers in neural networks, which expect a one-dimensional input.

In [ ]:
a.flatten()  # not affect original data

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
a        # not affected by " flatten "

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
c=t.tensor([[1,2],[3,4]])
print(c)

tensor([[1, 2],
        [3, 4]])


In [ ]:
c.flatten()

tensor([1, 2, 3, 4])

### Good work!