<a href="https://colab.research.google.com/github/IbukunGracey/PyTorch-Basics/blob/main/02_More_on_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.6.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.11.15
aiosignal                             1.3.2
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.6
ale-py                                0.11.0
altair                                5.5.0
annotated-types                       0.7.0
anyio                                 4.9.0
argon2-cffi                           23.1.0
argon2-cffi-bindings                  21.2.0
array_record                          0.7.2
arviz                                 0.21.0
astropy                               7.0.1
astropy-iers-data                     0.2025.4.28.0.37.27
astunparse                            1.6.3
atpublic                              5

### Tensors



*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar to Numpy arrays, but full of fun things that make them work better on GPUs (vs regular CPUs)
*   default data type of float32 can be changed to a different data type.
More suitable for deep learning that a numpy array



In [3]:
# IMPORT STATEMENTS
import torch as t
import numpy as np

### LISTS

In [4]:
#creating a list
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [5]:
#creating a list of lists
my_list2 = [[1,2,3,4], [1,2,3,4]]
my_list2

[[1, 2, 3, 4], [1, 2, 3, 4]]

### Numpy Arrays


In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.04126871, 0.18844935, 0.17374419, 0.84549656],
       [0.36807952, 0.95243036, 0.99368903, 0.39585099],
       [0.68308115, 0.8854687 , 0.06291646, 0.59192175]])

In [7]:
np1.dtype

dtype('float64')

### TENSORS

In [8]:
t_2d = t.randn(3,4)
t_2d

tensor([[-1.6764,  0.1021,  1.1167,  0.2351],
        [ 0.1494, -0.5053, -0.3449,  0.9826],
        [-0.1094, -0.2548,  0.2542,  0.2873]])

In [9]:
t_3d= t.zeros(2,3,4)
t_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array

new_tensor = t.tensor(np1)
new_tensor

tensor([[0.0413, 0.1884, 0.1737, 0.8455],
        [0.3681, 0.9524, 0.9937, 0.3959],
        [0.6831, 0.8855, 0.0629, 0.5919]], dtype=torch.float64)

#### See pytorch documentation for more on tensors - https://docs.pytorch.org/docs/stable/tensors.html

### TENSOR OPERATIONS FOR DEEP LEARNING WITH PYTORCH

In [11]:
# Create a new tensor with a range of 10 elements
my_torch = t.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Reshape

Although both torch.view and torch.reshape are used to reshape tensors, here are the differences between them.

`torch.reshape` doesn't impose any contiguity constraints, but also doesn't guarantee data sharing. The new tensor may be a view of the original tensor, or it may be a new tensor altogether.`

In [12]:
#Reshape the tensor
my_torch= my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
#Reshape using -1 if you don't know the shape of the items
my_torch2 = t.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
# 3 is used because it is a multiple of 15, if 2 is used, it will throw an error
my_torch2= my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [15]:
my_torch3 = my_torch2.reshape(5,-1) # this works
my_torch3

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [16]:
# -1 can also be used first
my_torch3 = my_torch2.reshape(-1,5) # this works
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [17]:
my_torch4 = my_torch2.reshape(2,-1)  # this won't work
my_torch4

RuntimeError: shape '[2, -1]' is invalid for input of size 15

#### View

As the name suggests, `torch.view` merely creates a view of the original tensor. The new tensor will always share its data with the original tensor. This means that if you change the original tensor, the reshaped tensor will change and vice versa.

To ensure that the new tensor always shares its data with the original, torch.view imposes some contiguity constraints on the shapes of the two tensors. More often than not this is not a concern, but sometimes torch.view throws an error even if the shapes of the two tensors are compatible.

TL;DR: If you just want to reshape tensors, use torch.reshape. If you're also concerned about memory usage and want to ensure that the two tensors share the same data, use torch.view.

In [19]:
#VIEW
my_torch5 = t.arange(10)
print(my_torch5)
my_view =my_torch5.view(2,5)
print(my_view)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


Note: With View and Reshape, when a shape is made in the original tensor, it updates the view and tge reshaped tensor

In [20]:
#update the element in location 0 to 20 in the view created
my_view[0,0]=20
my_view

tensor([[20,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [21]:
#Let's check the behaviour of the elemnet in the original tensor
#NOTE, the original tensor has also been updated
my_view

tensor([[20,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [22]:
# RESHAPE
# Let's see the behaviour of the reshape function
my_torch6 = t.arange(15)
print(my_torch6)
my_reshape =my_torch6.reshape(3,5)
print(my_reshape)

# my_tensor2 =torch.arange(10)
# my_tensor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [23]:
#Let's update the element in location 0 to 22 in the view created
my_reshape[0,0]=22
my_reshape

tensor([[22,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [24]:
#Let's check the behaviour of the element in the original tensor
#NOTE, the original tensor has also been updated just like the view
my_torch6

tensor([22,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Indexing and Slicing

In [25]:
my_torch7 = t.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#Index a specific item, element 8
my_torch7[8]

tensor(8)

In [27]:
#Grab a slice
my_torch8 = my_torch7.reshape(2,5)
my_torch8

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
# Grave a slice at column 5
my_torch8[:,4]

tensor([4, 9])

In [29]:
#To return a column to keep the structure
my_torch8[:,4:]

tensor([[4],
        [9]])

## TENSOR MATHS OPERATION

* Add, Subtract, Multiply, Divide, Remainder, Exponent
* Shorthand and Longhand
* Reassignment

In [30]:
a = t.tensor([4,5,6,7])
b = t.tensor([7,8,9,10])

In [31]:
#Addition shorthand
a+b

tensor([11, 13, 15, 17])

In [46]:
#Option 1 - Addition longhand
t.add(a,b)

tensor([11, 13, 15, 17])

In [47]:
#Option 2 -Addition longhand
a.add(b)

tensor([11, 13, 15, 17])

In [33]:
#Substraction shorthand
a - b

tensor([-3, -3, -3, -3])

In [34]:
#Substraction longhand
t.sub(a,b)

tensor([-3, -3, -3, -3])

In [35]:
#Multiplication shorthand
a * b

tensor([28, 40, 54, 70])

In [36]:
#Multiplication longhand
t.mul(a,b)

tensor([28, 40, 54, 70])

In [37]:
#Division shorthand
a/b

tensor([0.5714, 0.6250, 0.6667, 0.7000])

In [38]:
#Division longhand
t.div(a,b)

tensor([0.5714, 0.6250, 0.6667, 0.7000])

In [39]:
print(a)
print(b)

tensor([4, 5, 6, 7])
tensor([ 7,  8,  9, 10])


In [40]:
#Remainder Modulus
a % b

tensor([4, 5, 6, 7])

In [41]:
#Remainder longhand
t.remainder(a,b)

tensor([4, 5, 6, 7])

In [42]:
x = 5
y= 3
x%y

2

In [43]:
#Exponent/ Power
t.pow(a,b)

tensor([    16384,    390625,  10077696, 282475249])

In [53]:
#Tensor Reassignment_ (option1)
a = t.tensor([11, 13, 15, 17])
b = t.tensor([ 7,  8,  9, 10])
a = a + b
a

tensor([18, 21, 24, 27])

In [54]:
#Tensor Reassignment_ (option2)
a = t.tensor([11, 13, 15, 17])
b = t.tensor([ 7,  8,  9, 10])
a.add_(b)
a

tensor([18, 21, 24, 27])

In [55]:
#Note: This won't work
t.add_(a,b)

AttributeError: module 'torch' has no attribute 'add_'

### To Dos

1. Create two tensors,  x from a range of values 1 to 10 and y from a range of values 11 to 20.


In [60]:
x = t.arange(1,11)
y = t.arange(11,21)
print(x)
print(y)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


2. Reshape tensors x and y to 2 by 5



In [65]:
Q2a = x.reshape(2,5)
Q2a

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [66]:
Q2b=y.reshape(2,5)
Q2b

tensor([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

3. Index out 2,3,7,8 form tensor x and 14,15,19,20 from tensor y, retaining the tensors column style

In [68]:
Q2a[:, 1:3]

tensor([[2, 3],
        [7, 8]])

In [69]:
Q2b[:, 3:]

tensor([[14, 15],
        [19, 20]])